const mongoose=require('mongoose');
const Schema=mongoose.Schema;
const collegeSchema=new Schema({ 
    Sno: String,
    inst_code: String,
    inst_name: String,
    type: String,
    REG: String,
    DIST: String,
    PLACE: String,
    COED: String,
    AFFILIA: String,
    ESTD: Number,
    branch_code: String,
    OC_BOYS: Number,
    OC_GIRLS: Number,
    SC_BOYS: Number,
    SC_GIRLS: Number,
    ST_BOYS: Number,
    ST_GIRLS: Number,
    BCA_BOYS: Number,
    BCA_GIRLS: Number,
    BCB_BOYS: Number,
    BCB_GIRLS: Number,
    BCC_BOYS: Number,
    BCC_GIRLS: Number,
    BCD_BOYS: Number,
    BCD_GIRLS: Number,
    BCE_BOYS: Number,
    BCE_GIRLS: Number,
    OC_EWS_BOYS: Number,
    OC_EWS_GIRLS: Number,
    COLL_FEE: Schema.Types.Mixed,
},{timestamps:true});
const College=mongoose.model('College',collegeSchema);
module.exports=College;